services:
  server:
    image: node:20
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 5173:5173
      - 57778:57778 # vite HMR socket
    command: npm run dev -- --host

  redis:
    image: redis/redis-stack
    restart: unless-stopped
    ports:
      - 6379:6379
      - 8001:8001
